workflows:
  ios-build:
    name: MyStoryFootball iOS Build
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.terencedesrues.mystoryfootball"
        APPLE_TEAM_ID: "7B535ZNRSR"
        PROFILE_NAME: "MyStoryFoot_appstore"
    scripts:
      - name: CocoaPods install
        script: |
          pod install --repo-update || true
      - name: Build archive
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            archive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME"
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
