      - name: Build React app with correct config
        script: |
          echo "Building with Vite using vite.config.ts..."
          npx vite build
          echo "Building server..."
          npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
          echo "Build completed, checking output..."
          ls -la dist/
          ls -la dist/public/
