workflows:
  ios-sign-only:
    name: DEBUG + Sign iOS App
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.terencedesrues.mystoryfootball
      xcode: 15.0
    scripts:
      - name: Create exportOptions.plist
        script: |
          cd ios/App
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>destination</key>
              <string>export</string>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>7B535ZN5R</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
          echo "=== exportOptions.plist créé ==="
          cat exportOptions.plist
      - name: DEBUG et signature
        script: |
          cd ios/App
          echo "=== EMPLACEMENT ET FICHIERS ==="
          pwd
          ls -la
          echo ""
          echo "=== VÉRIFICATION WORKSPACE ==="
          ls -la App.xcworkspace
          ls -la App.xcworkspace/contents.xcworkspacedata
          echo ""
          echo "=== VÉRIFICATION VARIABLES CODEMAGIC ==="
          echo "TEAM_ID (configuré): '7B535ZN5R'"
          echo "PROFILE_SPECIFIER (configuré): 'MyStoryFoot_appstore'"
          echo ""
          echo "=== DÉMARRAGE BUILD AVEC VALEURS FIXES ==="
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            DEVELOPMENT_TEAM="7B535ZN5R" \
            PROVISIONING_PROFILE_SPECIFIER="MyStoryFoot_appstore"
          echo ""
          echo "=== EXPORT IPA ==="
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist
          echo ""
          echo "=== RÉSULTAT FINAL ==="
          ls -la build/
          ls -la build/ipa/ || echo "Dossier ipa introuvable"
    artifacts:
      - ios/App/build/**/*.ipa
      - ios/App/build/*.ipa
