workflows:
  ios-workflow:
    name: iOS Build (Capacitor)
    environment:
      node: 20
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        DEV_TEAM: "7B535ZNRSR"                   # <- ton Team ID (corrigé)
        PROFILE_SPECIFIER: "MyStoryFoot_appstore" # <- nom EXACT du provisioning profile
    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install CocoaPods (inside ios/App)
        script: |
          cd ios/App
          pod repo update
          pod install
          ls -la
          test -d "App.xcworkspace" || { echo "❌ App.xcworkspace manquant"; exit 1; }

      - name: Build iOS (archive + export IPA)
        script: |
          mkdir -p "$CM_BUILD_DIR/ios_output"

          # Archive
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            archive \
            -archivePath "$CM_BUILD_DIR/ios_output/App.xcarchive" \
            "CODE_SIGN_IDENTITY=Apple Distribution" \
            "DEVELOPMENT_TEAM=$DEV_TEAM" \
            "PROVISIONING_PROFILE_SPECIFIER=$PROFILE_SPECIFIER"

          # Export IPA (utilise ton exportOptions.plist placé dans ios/App)
          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/ios_output/App.xcarchive" \
            -exportOptionsPlist "ios/App/exportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/ios_output"

    artifacts:
      - $CM_BUILD_DIR/ios_output/*.ipa
      - $CM_BUILD_DIR/ios_output/**/*.dSYM.zip
      - $CM_BUILD_DIR/ios_output/*.xcarchive
