workflows:
  ios-workflow:
    name: iOS Build (direct)
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.terencestories.mystoryfootball"
        APPLE_TEAM_ID: "7853SZN5R"
        CODE_SIGN_IDENTITY: "Apple Distribution"
        PROVISIONING_PROFILE_SPECIFIER: "MyStoryFootball_Provision"
    scripts:
      - name: Install CocoaPods
        script: |
          cd MyStoryFootball
          pod install --repo-update
      - name: Build ipa
        script: |
          cd MyStoryFootball
          xcodebuild \
            -workspace "App.xcworkspace" \
            -scheme "App" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive archive \
            CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID"
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            -exportPath $CM_BUILD_DIR/build \
            -exportOptionsPlist exportOptions.plist
    artifacts:
      - build/*.ipa
