workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      node: 20
      cocoapods: default
    scripts:
      - npm install
      - npx cap sync ios
      - cd ios && pod install
      - xcodebuild \
          -workspace "ios/App/App.xcworkspace" \
          -scheme "App" \
          -sdk iphoneos \
          -configuration Release \
          archive \
          -archivePath $CM_BUILD_DIR/Runner.xcarchive \
          -allowProvisioningUpdates
      - xcodebuild -exportArchive \
          -archivePath $CM_BUILD_DIR/Runner.xcarchive \
          -exportOptionsPlist ios/exportOptions.plist \
          -exportPath $CM_BUILD_DIR \
          -allowProvisioningUpdates
    artifacts:
      - $CM_BUILD_DIR/*.ipa
    code_signing:
      ios:
        automatic_code_signing: true
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
