workflows:
  ios-ultra-simple:
    name: My Story Football - Ultra Simple
    max_build_duration: 25
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.terencedesrues.mystoryfootball
      xcode: 15.0
    scripts:
      - name: Build iOS avec gestion automatique complete
        script: |
          cd ios/App
          
          echo "=== NETTOYAGE ==="
          rm -rf build/
          rm -rf DerivedData/
          
          echo "=== WORKSPACE VERIFIE ==="
          ls -la App.xcworkspace/contents.xcworkspacedata
          echo "Workspace OK ✅"
          
          echo "=== BUILD AUTOMATIQUE TOTAL ==="
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "build/App.xcarchive" \
            archive \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=7B535ZN5R \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="MyStoryFoot_appstore" \
            -allowProvisioningUpdates \
            -allowProvisioningDeviceRegistration
          
          echo "=== EXPORT SIMPLE ==="
          xcodebuild \
            -exportArchive \
            -archivePath "build/App.xcarchive" \
            -exportPath "build/ipa" \
            -exportOptionsPlist <(cat << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>method</key>
    <string>app-store</string>
    <key>teamID</key>
    <string>7B535ZN5R</string>
    <key>signingStyle</key>
    <string>automatic</string>
    <key>uploadBitcode</key>
    <false/>
    <key>uploadSymbols</key>
    <true/>
    <key>compileBitcode</key>
    <false/>
</dict>
</plist>
EOF
) \
            -allowProvisioningUpdates
          
          echo "=== RESULTAT ==="
          find build/ipa/ -name "*.ipa" -exec ls -lh {} \;
    artifacts:
      - ios/App/build/ipa/*.ipa