workflows:
  ios-workflow:
    name: iOS Build
    environment:
      vars:
        XCODE_WORKSPACE: "App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.terencedesrues.mystoryfootball"
      xcode: latest
      node: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          cd App
          npm install
      - name: Install CocoaPods
        script: |
          cd App
          pod install
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace "App/App.xcworkspace" \
            -scheme "App" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=7B535ZNRSR \
            PROVISIONING_PROFILE_SPECIFIER=MyStoryFoot_appstore
    artifacts:
      - App/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        password: $APP_SPECIFIC_PASSWORD
