workflows:
  ios-test:
    name: iOS Test Build - My Story Football
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "com.mystoryfootball.app"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: npm ci
      - name: Build React app
        script: npm run build
      - name: Add iOS platform
        script: npx cap add ios --confirm
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Build iOS app (unsigned)
        script: |
          cd ios/App && xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -destination generic/platform=iOS \
            archive \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/build/**/*.xcarchive
