workflows:
  ios-workflow:
    name: MyStoryFootball iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.terencedesrues.mystoryfootball"
        CODE_SIGN_STYLE: "Manual"
        DEVELOPMENT_TEAM: "7B535ZNRSR"
        PROVISIONING_PROFILE_SPECIFIER: "Mon provision"
        CODE_SIGN_IDENTITY: "Apple Distribution"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods
        script: |
          cd App
          pod install
      - name: Build archive
        script: |
          xcodebuild archive \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $CM_BUILD_DIR/ios_output/MyApp.xcarchive \
          DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
          CODE_SIGN_STYLE="$CODE_SIGN_STYLE" \
          PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
          CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
          PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID"
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
          -archivePath $CM_BUILD_DIR/ios_output/MyApp.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath $CM_BUILD_DIR/ios_output
    artifacts:
      - $CM_BUILD_DIR/ios_output/*.ipa
      - $CM_BUILD_DIR/ios_output/*.dSYM.zip
      - $CM_BUILD_DIR/ios_output/*.xcarchive
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
