workflows:
  ios-workflow:
    name: iOS Build
    environment:
      vars:
        TEAM_ID: 785S52NSR
        PROFILE_SPECIFIER: MyStoryFoot_appstore
      xcode: latest
      cocoapods: default
    scripts:
      - name: Post-clone fix
        script: |
          chmod +x ios/post-clone.sh
          ./ios/post-clone.sh

      - name: Install dependencies
        script: |
          npm install
          npx cap sync ios

      - name: Build iOS
        script: |
          xcodebuild \
            -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -sdk iphoneos \
            -configuration Release \
            DEVELOPMENT_TEAM=$TEAM_ID \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER=$PROFILE_SPECIFIER \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            archive -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios_output
