workflows:
  ios-sign-only:
    name: Sign + IPA Only
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.terencedesrues.mystoryfootball
      xcode: 15.0
    scripts:
      - name: Sign and create IPA
        script: |
          cd ios/App
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            DEVELOPMENT_TEAM="$CM_CERTIFICATE_TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$CM_PROVISIONING_PROFILE"
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist
          ls -la build/ipa/
    artifacts:
      - ios/App/build/**/*.ipa
