workflows:
  ios-app-store:
    name: Build iOS App Store
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.terencedesrues.mystoryfootball
      xcode: 15.0
    scripts:
      - name: Create shared scheme
        script: |
          cd ios/App/App.xcodeproj
          mkdir -p xcshareddata/xcschemes
          cat > xcshareddata/xcschemes/App.xcscheme << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <Scheme
             LastUpgradeVersion = "1500"
             version = "1.3">
             <BuildAction
                parallelizeBuildables = "YES"
                buildImplicitDependencies = "YES">
                <BuildActionEntries>
                   <BuildActionEntry
                      buildForTesting = "YES"
                      buildForRunning = "YES"
                      buildForProfiling = "YES"
                      buildForArchiving = "YES"
                      buildForAnalyzing = "YES">
                      <BuildableReference
                         BuildableIdentifier = "primary"
                         BlueprintIdentifier = "504EC3031FED79650016851F"
                         BuildableName = "App.app"
                         BlueprintName = "App"
                         ReferencedContainer = "container:App.xcodeproj">
                      </BuildableReference>
                   </BuildActionEntry>
                </BuildActionEntries>
             </BuildAction>
             <TestAction
                buildConfiguration = "Debug"
                selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
                selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
                shouldUseLaunchSchemeArgsEnv = "YES">
             </TestAction>
             <LaunchAction
                buildConfiguration = "Debug"
                selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
                selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
                launchStyle = "0"
                useCustomWorkingDirectory = "NO"
                ignoresPersistentStateOnLaunch = "NO"
                debugDocumentVersioning = "YES"
                debugServiceExtension = "internal"
                allowLocationSimulation = "YES">
                <BuildableProductRunnable
                   runnableDebuggingMode = "0">
                   <BuildableReference
                      BuildableIdentifier = "primary"
                      BlueprintIdentifier = "504EC3031FED79650016851F"
                      BuildableName = "App.app"
                      BlueprintName = "App"
                      ReferencedContainer = "container:App.xcodeproj">
                   </BuildableReference>
                </BuildableProductRunnable>
             </LaunchAction>
             <ProfileAction
                buildConfiguration = "Release"
                shouldUseLaunchSchemeArgsEnv = "YES"
                savedToolIdentifier = ""
                useCustomWorkingDirectory = "NO"
                debugDocumentVersioning = "YES">
                <BuildableProductRunnable
                   runnableDebuggingMode = "0">
                   <BuildableReference
                      BuildableIdentifier = "primary"
                      BlueprintIdentifier = "504EC3031FED79650016851F"
                      BuildableName = "App.app"
                      BlueprintName = "App"
                      ReferencedContainer = "container:App.xcodeproj">
                   </BuildableReference>
                </BuildableProductRunnable>
             </ProfileAction>
             <AnalyzeAction
                buildConfiguration = "Debug">
             </AnalyzeAction>
             <ArchiveAction
                buildConfiguration = "Release"
                revealArchiveInOrganizer = "YES">
             </ArchiveAction>
          </Scheme>
          EOF
          
      - name: Setup Pods
        script: |
          cd ios/App
          pod install --repo-update
          
      - name: Build iOS App
        script: |
          cd ios/App
          
          # Créer exportOptions.plist
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>7B535ZN5R</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
          
          # Vérifier le scheme
          xcodebuild -list -workspace App.xcworkspace
          
          # Build Archive (SANS MODIFIER LE PROJECT)
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            DEVELOPMENT_TEAM="7B535ZN5R" \
            PROVISIONING_PROFILE_SPECIFIER="MyStoryFoot_appstore" \
            CODE_SIGN_STYLE="Automatic" \
            -allowProvisioningUpdates
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist \
            -allowProvisioningUpdates
          
          ls -la build/ipa/
          
    artifacts:
      - ios/App/build/ipa/*.ipa
