workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      node: 20
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          cd ios
          xcodebuild \
            -workspace "App/App.xcworkspace" \
            -scheme "App" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/build/**/*.ipa
    publishing:
      email:
        recipients:
          - "ton-email@exemple.com"
  publishing:
  app_store_connect:
    api_key: $APP_STORE_CONNECT_PRIVATE_KEY      # contenu du fichier .p8
    key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER    # Key ID
    issuer_id: $APP_STORE_CONNECT_ISSUER_ID      # Issuer ID
    submit_to_testflight: true                   # envoi automatique sur TestFlight
    submit_to_app_store: false                   # reste en TestFlight, tu soumets après manuellement
