workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        provisioning_profiles:
          - MyStoryFoot_appstore
        certificates:
          - MY_CERTIFICATE
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          cd App
          pod install

      - name: Build iOS
        script: |
          cd App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive archive \
            DEVELOPMENT_TEAM=7B535ZNRSR \
            PROVISIONING_PROFILE_SPECIFIER="MyStoryFoot_appstore" \
            CODE_SIGN_IDENTITY="Apple Distribution"

      - name: Export .ipa
        script: |
          cd App
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportPath $CM_BUILD_DIR \
            -exportOptionsPlist exportOptions.plist

    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/App.xcarchive
