workflows:
  ios-app-store:
    name: Build iOS App Store
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.terencedesrues.mystoryfootball
      xcode: 15.0
    scripts:
      - name: Fix project.pbxproj with surgical edits
        script: |
          cd ios/App/App.xcodeproj
          echo "=== Backup original file ==="
          cp project.pbxproj project.pbxproj.backup
          
          echo "=== Remove problematic CODE_SIGN_IDENTITY lines ==="
          sed -i '' '/CODE_SIGN_IDENTITY = "iPhone Developer";/d' project.pbxproj
          
          echo "=== Add DEVELOPMENT_TEAM in TargetAttributes ==="
          sed -i '' '/ProvisioningStyle = Automatic;/a\
						DevelopmentTeam = 7B535ZN5R;' project.pbxproj
          
          echo "=== Add DEVELOPMENT_TEAM in Debug config ==="
          sed -i '' '/ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;/a\
				DEVELOPMENT_TEAM = 7B535ZN5R;' project.pbxproj
          
          echo "=== Verify syntax ==="
          plutil -lint project.pbxproj
          if [ $? -ne 0 ]; then
            echo "=== Syntax error detected, restoring backup ==="
            cp project.pbxproj.backup project.pbxproj
            echo "=== Manual fix attempt ==="
            # Remove the problematic lines more carefully
            grep -v 'CODE_SIGN_IDENTITY = "iPhone Developer"' project.pbxproj.backup > project.pbxproj.temp
            mv project.pbxproj.temp project.pbxproj
          fi
          
          echo "=== Final verification ==="
          head -20 project.pbxproj
          
      - name: Create exportOptions.plist
        script: |
          cd ios/App
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>destination</key>
              <string>export</string>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>7B535ZN5R</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
          
      - name: Build and Archive iOS
        script: |
          cd ios/App
          echo "=== Nettoyage build ==="
          rm -rf build/
          mkdir -p build/
          echo ""
          echo "=== Archive iOS ==="
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            DEVELOPMENT_TEAM="7B535ZN5R" \
            CODE_SIGN_STYLE="Automatic" \
            -allowProvisioningUpdates
          echo ""
          echo "=== Export IPA ==="
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist \
            -allowProvisioningUpdates
          echo ""
          echo "=== Résultat final ==="
          ls -la build/ipa/
          
    artifacts:
      - ios/App/build/ipa/*.ipa
