workflows:
  ios-app-store:
    name: iOS App Store Submission - My Story Football
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "com.terencedesrues.mystoryfootball"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20.12.0
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.terencedesrues.mystoryfootball
    integrations:
      capacitor: false   # ✅ Désactive l'étape auto "Add iOS platform"
    scripts:
      - name: Install Capacitor dependencies
        script: |
          npm install @capacitor/core @capacitor/cli @capacitor/ios --legacy-peer-deps
      - name: Verify pre-built files
        script: |
          echo "Using pre-built files from dist/..."
          ls -la dist/
          ls -la dist/public/
          echo "All files ready for Capacitor!"
          echo "iOS platform already exists, skipping add step"
          ls -la ios/
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      - name: Build iOS app for App Store
        script: |
          cd ios/App && xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -destination generic/platform=iOS \
            -archivePath build/MyStoryFootball.xcarchive \
            archive
      - name: Export IPA for App Store
        script: |
          cd ios/App && xcodebuild \
            -exportArchive \
            -archivePath build/MyStoryFootball.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist
    artifacts:
      - ios/App/build/**/*.ipa
      - ios/App/build/**/*.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        submit_to_app_store: true
        cancel_previous_submissions: true
        release_type: MANUAL
        submit_to_testflight: true
      email:
        recipients:
          - terence.desrues@example.com
        notify:
          success: true
          failure: true
