workflows:
  ios-workflow:
    name: iOS Build and Publish
    environment:
      node: 20
      vars:
        XCODE_WORKSPACE: "ios/App.xcworkspace"
        XCODE_SCHEME: "App"   # remplace par ton vrai scheme Xcode
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="MyStoryFoot_appstore" \
            DEVELOPMENT_TEAM="7N63S25N5R"
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios_output
    artifacts:
      - $CM_BUILD_DIR/ios_output/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY   # contenu du .p8
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER # Key ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID   # Issuer ID
        submit_to_testflight: true
