workflows:
  ios-workflow:
    name: iOS Build
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install npm dependencies
        script: |
          cd App
          npm install
      - name: Capacitor sync
        script: |
          cd App
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd App/ios/App
          pod install
      - name: Build iOS
        script: |
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos
    artifacts:
      - App/ios/App/build/**/*.ipa
