workflows:
  ios-sign-only:
    name: Sign + IPA Only
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.terencedesrues.mystoryfootball
      xcode: 15.0
    scripts:
      - name: Create exportOptions.plist
        script: |
          cd ios/App
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>destination</key>
              <string>export</string>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>\$CM_CERTIFICATE_TEAM_ID</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
      - name: Sign and create IPA
        script: |
          cd ios/App
          xcodebuild archive \
            -project App.xcodeproj \
            -scheme App \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            DEVELOPMENT_TEAM="$CM_CERTIFICATE_TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$CM_PROVISIONING_PROFILE"
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist
          ls -la build/ipa/
    artifacts:
      - ios/App/build/**/*.ipa
