workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        BUNDLE_ID: "com.terencedesrues.mystoryfootball"
        TEAM_ID: "7B535ZNRSR"
        XCODE_WORKSPACE: "App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: latest
      xcode: latest

    scripts:
      - name: Install npm dependencies
        script: |
          cd App
          npm install
      - name: Capacitor sync
        script: |
          cd App
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd App
          pod install
      - name: Build iOS
        script: |
          cd App
          xcodebuild \
            -workspace $XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=$TEAM_ID \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
            build

    artifacts:
      - App/build/ios/ipa/*.ipa
