workflows:
  ios-workflow:
    name: iOS Build (Capacitor)
    environment:
      xcode: 16.4
      node: 20

    scripts:
      - name: Install deps
        script: npm install

      - name: Sync Capacitor
        script: npx cap sync ios

      - name: Install CocoaPods (génère le .xcworkspace)
        script: |
          cd ios/App
          pod repo update
          pod install

      - name: Build iOS (archive + export IPA)
        script: |
          mkdir -p $CM_BUILD_DIR/ios_output
          xcodebuild \
            -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            DEVELOPMENT_TEAM=7N63S25N5R \
            CODE_SIGN_STYLE=Automatic
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios_output

    artifacts:
      - $CM_BUILD_DIR/ios_output/*.ipa

    publishing:
      app_store_connect:
        # Ajoute bien ces 3 secrets dans Codemagic > App settings > Environment variables (secure)
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
