workflows:
  ios-workflow:
    name: iOS Build (Capacitor)
    environment:
      xcode: 16.4
      node: 20
      vars:
        TEAM_ID: $TEAM_ID
        PROFILE_SPECIFIER: $PROFILE_SPECIFIER
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY

    scripts:
      - name: Install deps
        script: npm install

      - name: Sync Capacitor
        script: npx cap sync ios

      - name: Install CocoaPods (génère le .xcworkspace)
        script: |
          cd ios/App
          pod repo update
          pod install

      - name: Build iOS (archive + export IPA)
        script: |
          mkdir -p $SCM_BUILD_DIR/ios_output

          # Archive l'app
          xcodebuild \
            -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath $SCM_BUILD_DIR/ios_output/App.xcarchive \
            DEVELOPMENT_TEAM=$TEAM_ID \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution"

          # Export IPA avec exportOptions.plist
          xcodebuild \
            -exportArchive \
            -archivePath $SCM_BUILD_DIR/ios_output/App.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $SCM_BUILD_DIR/ios_output

    artifacts:
      - $SCM_BUILD_DIR/ios_output/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
