workflows:
  ios-workflow:
    name: iOS Build & Publish
    environment:
      node: 20.11.1          # Node.js LTS pour Capacitor
      xcode: 15.2            # Version Xcode compatible iOS 17
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS app
        script: |
          npx cap build ios
          cd ios
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="MyStoryFoot_appstore" \
            DEVELOPMENT_TEAM="7B63Z5NSHR"
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios_output
    artifacts:
      - ios_output/**/*.ipa
    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        password: $APP_STORE_CONNECT_PASSWORD
        app_identifier: com.terencedesrues.mystoryfootball
        bundle_identifier: com.terencedesrues.mystoryfootball
        submit_to_testflight: true
        submit_to_app_store: false
