workflows:
  ios-build:
    name: iOS Build
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.terencedesures.mystoryfootball"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx pod-install ios
      - name: Run post-clone script
        script: |
          chmod +x ios/post-clone.sh
          ./ios/post-clone.sh
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            DEVELOPMENT_TEAM=$TEAM_ID \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER=$PROFILE_SPECIFIER \
            CODE_SIGN_IDENTITY="Apple Distribution"
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios_output
    artifacts:
      - ios_output/*.ipa
    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APPLE_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APPLE_STORE_CONNECT_ISSUER_ID
