workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      vars:
        XCODE_WORKSPACE: "App/App.xcworkspace"
        XCODE_SCHEME: "App"
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Capacitor sync
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd App
          pod install
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/ios_build/App.xcarchive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=7B535ZNRSR \
            PROVISIONING_PROFILE_SPECIFIER="MyStoryFoot_appstore"
    artifacts:
      - ios_build/**/*.xcarchive
      - $CM_BUILD_DIR/ios_build/**/*.ipa
