workflows:
  ios-workflow:
    name: iOS Build and Publish
    environment:
      node: 20
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Install CocoaPods
        script: cd ios/App && pod install && cd ../..
      - name: Build iOS (archive + export IPA)
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="MyStoryFoot_appstore" \
            DEVELOPMENT_TEAM="7B535ZNRSR"

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios_output
    artifacts:
      - $CM_BUILD_DIR/ios_output/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
