workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.terencedesrues.mystoryfootball"
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.terencedesrues.mystoryfootball"
        TEAM_ID: $TEAM_ID
        PROFILE_SPECIFIER: $PROFILE_SPECIFIER
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap sync ios
          cd ios/App && pod install && cd ../..
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath $SCM_BUILD_DIR/ios_output/App.xcarchive \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_SPECIFIER" \
            CODE_SIGN_IDENTITY="Apple Distribution"

          xcodebuild -exportArchive \
            -archivePath $SCM_BUILD_DIR/ios_output/App.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $SCM_BUILD_DIR/ios_output
    artifacts:
      - ios_output/*.ipa
      - ios_output/*.xcarchive
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APPLE_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APPLE_STORE_CONNECT_ISSUER_ID
