workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.terencedesrues.mystoryfootball"
        XCODE_WORKSPACE: "ios/App.xcworkspace"
        XCODE_SCHEME: "App"
    scripts:
      - name: Install dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/build/**/*.ipa
    publishing:
      email:
        recipients:
          - "ton-email@exemple.com"
