workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: "MyStoryFootball/App.xcodeproj"
        XCODE_SCHEME: "MyStoryFootball"
        BUNDLE_ID: "com.terencedesrues.mystoryfootball"
    scripts:
      - name: Install CocoaPods
        script: |
          cd MyStoryFootball
          pod install
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace MyStoryFootball/App.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=7B535ZNRSR \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
            PROVISIONING_PROFILE_SPECIFIER=MyStoryFoot_appstore \
            archive -archivePath $CM_BUILD_DIR/ios_archive.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_archive.xcarchive \
            -exportOptionsPlist MyStoryFootball/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
    publishing:
      email:
        recipients:
          - "ton-email@exemple.com"
