workflows:
  ios-workflow:
    name: iOS Build and Publish
    environment:
      node: 20
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"   # change si ton scheme a un autre nom
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="MyStoryFoot_appstore" \
            DEVELOPMENT_TEAM="7N63S25N5R"

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            -exportPath $CM_BUILD_DIR/ios_output \
            -allowProvisioningUpdates
    artifacts:
      - $CM_BUILD_DIR/ios_output/*.ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER   # exemple : 2X9R4HXF34
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID     # exemple : 57246542-96fe-1a63-e053-0824d011072a
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY # colle le contenu de ton .p8 dans une variable secrète
        submit_to_testflight: true
        submit_to_app_store: false
