workflows:
  ios-app-store:
    name: iOS App Store - My Story Football
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.terencedesrues.mystoryfootball
        signing_config: automatic
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_ID: $APP_STORE_CONNECT_KEY_ID
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
      xcode: 15.0
      node: 20.0.0
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Build React app
        script: |
          npm run build
      - name: Capacitor sync iOS
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      - name: Build iOS archive
        script: |
          cd ios/App
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            DEVELOPMENT_TEAM="$CM_CERTIFICATE_TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$CM_PROVISIONING_PROFILE"
      - name: Export IPA
        script: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist
          ls -la build/ipa/
          find build/ -name "*.ipa" -type f
    artifacts:
      - ios/App/build/**/*.ipa
      - ios/App/build/*.ipa  
      - ios/App/build/App.xcarchive
      - $CM_BUILD_DIR/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
