workflows:
  ios-app:
    name: iOS Build
    environment:
      xcode: 15.0   # tu peux changer en 14.3 si besoin
      vars:
        BUNDLE_ID: "com.terencedesrues.mystoryfootball"
      ios_signing:
        certificates:
          - MyStoryFoot_appstore   # le nom que tu as donné à ton .p12 dans Codemagic
        provisioning_profiles:
          - MyStoryFoot_appstore   # le nom de ton provisioning profile dans Codemagic
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/Build/App.xcarchive \
            archive
