workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: 15.0
      node: 20.11.0   # Node.js >= 20 pour éviter l'erreur Capacitor
      cocoapods: default
      vars:
        BUNDLE_ID: "com.terencedesrues.mystoryfootball"
      ios_signing:
        certificates:
          - MyStoryFoot_appstore
        provisioning_profiles:
          - MyStoryFoot_appstore

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/Build/App.xcarchive \
            archive

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/Build/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/Build

    artifacts:
      - $CM_BUILD_DIR/Build/*.ipa
      - $CM_BUILD_DIR/Build/*.xcarchive

    publishing:
      app_store_connect:
        apple_id: "ton_email_apple@icloud.com"
        password: "@env:APP_STORE_CONNECT_PASSWORD"
        app_identifier: "com.terencedesrues.mystoryfootball"
