workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        XCODE_WORKSPACE: "App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.terencedesrues.mystoryfootball"
        DEVELOPMENT_TEAM: "7B535ZNRSR"
        CODE_SIGN_IDENTITY: "Apple Distribution"
        CODE_SIGN_STYLE: "Manual"
        PROVISIONING_PROFILE_SPECIFIER: "Mon provision"
      node: 18
      xcode: 15.4

    scripts:
      - name: Install npm dependencies
        script: |
          cd App
          npm install
      - name: Capacitor sync
        script: |
          cd App
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd App
          pod install
      - name: Build archive
        script: |
          xcodebuild archive \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $CM_BUILD_DIR/ios_output/MyApp.xcarchive \
          DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
          CODE_SIGN_STYLE="$CODE_SIGN_STYLE" \
          PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
          CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
          PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID"

    artifacts:
      - ios_output/*.xcarchive
      - $CM_BUILD_DIR/ios_output/*.ipa

    publishing:
      email:
        recipients:
          - "ton_email@icloud.com"
