workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.terencedesrues.mystoryfootball"
      xcode_workspace: "ios/App/App.xcworkspace"
      xcode_scheme: "MyStoryFootball"
      bundle_id: "com.terencedesrues.mystoryfootball"
      team_id: $TEAM_ID
      profile_specifier: $PROFILE_SPECIFIER
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap sync ios
          cd ios/App
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ../..
      - name: Set up keychain
        script: keychain initialize
      - name: Build iOS
        script: |
          mkdir -p ios_output
          xcodebuild \
            -workspace "$xcode_workspace" \
            -scheme "$xcode_scheme" \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            DEVELOPMENT_TEAM=$team_id \
            PROVISIONING_PROFILE_SPECIFIER=$profile_specifier \
            CODE_SIGN_IDENTITY="Apple Distribution"

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios_output
    artifacts:
      - ios_output/*.ipa
      - ios_output/*.xcarchive
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
