workflows:
  ios-manual-signing:
    name: My Story Football - Manuel
    max_build_duration: 25
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.terencedesrues.mystoryfootball
      xcode: 15.0
    scripts:
      - name: Build iOS signature manuelle
        script: |
          cd ios/App
          
          echo "=== NETTOYAGE ==="
          rm -rf build/
          rm -rf DerivedData/
          
          echo "=== WORKSPACE VERIFIE ==="
          ls -la App.xcworkspace/contents.xcworkspacedata
          echo "Workspace OK ✅"
          
          echo "=== BUILD SIGNATURE MANUELLE ==="
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "build/App.xcarchive" \
            archive
          
          echo "=== EXPORT MANUEL ==="
          xcodebuild \
            -exportArchive \
            -archivePath "build/App.xcarchive" \
            -exportPath "build/ipa" \
            -exportForAppStore
          
          echo "=== RESULTAT ==="
          find build/ipa/ -name "*.ipa" -exec ls -lh {} \;
    artifacts:
      - ios/App/build/ipa/*.ipa
