platform :ios, '13.0'
use_frameworks!

# Ignore all warnings from all pods
inhibit_all_warnings!

def capacitor_pods
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'App' do
  capacitor_pods

  # Ajoute ici les plugins Capacitor si tu en utilises
  # Exemple :
  # pod 'CapacitorCommunityHttp', :path => '../node_modules/@capacitor-community/http'
end
