platform :ios, '14.0'
use_frameworks!
use_modular_headers!

target 'App' do
  pod 'Capacitor'
  pod 'CapacitorCordova'
  
  # ⚡️ ajoute ici d’autres pods si ton app en a besoin
  # pod 'Firebase/Core'
  # pod 'Firebase/Auth'
end
